version: "3.7"
services:
  #PHP Service
  lara_vue:
    build:
      args:
        user: dream71
        uid: 1000
      context: .
      dockerfile: .docker/Dockerfile
    image: lara_vue
    restart: unless-stopped
    working_dir: /var/www/
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lara_vue_network

  #MySQL Service
  lara_vue_db:
    image: mysql:8.0
    container_name: lara_vue_db
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - lara_vue_mysql_data:/var/lib/mysql
    networks:
      - lara_vue_network

  #Nginx Service
  lara_vue_nginx:
    image: nginx:alpine
    container_name: lara_vue_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
      - "${DOCKER_APP_SSL_PORT}:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - lara_vue_network
  # phpmyadmin service
  bscic_ecom_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: lara_vue_phpmyadmin
    depends_on:
      - lara_vue_db
    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:81"
    environment:
      PMA_HOST: lara_vue_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 500M
    networks:
      - lara_vue_network

  bscic_ecom_redis_cache:
    image: redis:alpine
    restart: always
    container_name: lara_vue_redis_cache
    ports:
      - '${DOCKER_REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - lara_vue_cache:/data
    networks:
      - lara_vue_network

#Docker Networks
networks:
 lara_vue_network:
    driver: bridge

#Volumes
volumes:
 lara_vue_mysql_data:
 lara_vue_cache:
